export type ReadingUiLocale = "zh" | "en" | "ja";

export const READING_UI = {
  zh: {
    brand: "屋顶现视研",
    nav: ["专题", "连载", "文库", "关于"],
    introduction: "导读",
    contents: "目录",
    figures: "图表",
    bookContents: "全书目录",
    readingProgress: "阅读进度",
    line: "行",
    noSections: "本文没有分节标题，可按视觉行定位。",
    untitledSection: (index: number) => `第 ${index} 节`,
    forthcoming: "待更新",
    copy: "复制",
    download: "下载",
    backToTop: "返回篇首",
    credits: "署名",
    author: "作者",
    roleLabels: {
      author: "作者", interviewee: "受访", interviewer: "采访", participant: "与谈",
      speaker: "主讲", translator: "译者", reviewer: "审阅", proofreader: "校对", editor: "编辑",
    },
    roleMarks: {
      author: "作", interviewee: "访", interviewer: "采", participant: "谈",
      speaker: "讲", translator: "译", reviewer: "审", proofreader: "校", editor: "编",
    },
    annotation: "注释",
    source: "文献",
    annotationSingular: "注释",
    sourceSingular: "文献",
    noReference: (kind: string) => `本文没有${kind}。`,
    firstReference: (kind: string) => `首条${kind}`,
    lastReference: (kind: string) => `末条${kind}`,
    sourcePosition: "原文位置",
    youAreReading: "您正在读",
    updateBoundary: "文章更新边界",
    readUntil: "上次读完至此",
    updatedBelow: "以下为更新内容",
    settings: "阅读习惯",
    globalNav: "全站导航",
    theme: "切换明暗主题",
    close: "关闭",
    back: "返回",
    fontFamily: "字族",
    serif: "衬线",
    sans: "无衬线",
    fontSize: "字号",
    sizes: ["小", "中", "大"],
    sample: "字",
    lightTheme: "切换到浅色",
    darkTheme: "切换到深色",
    readingRecords: "阅读记录",
    saveReadingRecords: "保存本机阅读记录",
    readingRecordsNote: "默认开启；记录仅保存在当前浏览器，不会上传或跨设备同步。",
    clearCurrent: "清除本文记录",
    clearAll: "清除全部记录",
    clearAllConfirm: "确定清除当前浏览器中的全部阅读记录吗？",
    viewTable: "查看文后表格",
    expand: "展开",
    collapse: "折叠",
    subsections: "的下级标题",
    articleActions: "文章操作",
    figure: "图",
    table: "表",
    jumpToLine: "按正文视觉行跳转",
    lineCountPending: "正文行数正在计算",
    articleContents: "文章目录",
    figureIndex: "文章图表索引",
    referenceJump: (kind: string) => `按序号跳转${kind}`,
    referenceInput: (kind: string, count: number) => `输入${kind}序号，共 ${count} 条`,
    referenceCurrent: (kind: string, current: number) => `当前第 ${current} 条${kind}，点击输入序号跳转`,
    home: "返回屋顶现视研首页",
    progressMessages: {
      appended: "文章已有新增内容，已回到上次读完的位置",
      approximate: "文章已更新，已恢复到上次位置附近",
      restored: "已恢复到上次阅读位置",
      disabled: "已停止保存本机阅读记录",
      disabledNotStored: "本页已停止保存；浏览器未能记住此设置",
      enabled: "已开启本机阅读记录",
      enabledNotStored: "本页已开启保存；浏览器未能记住此设置",
      clearCurrentFailed: "浏览器未能清除本文阅读记录",
      clearCurrentDone: "已清除本文阅读记录",
      clearAllFailed: "浏览器未能清除全部阅读记录",
      clearAllDone: "已清除全部阅读记录",
    },
  },
  en: {
    brand: "Lab on Roof",
    nav: ["Topics", "Series", "Library", "About"],
    introduction: "Introduction",
    contents: "Contents",
    figures: "Figures",
    bookContents: "Book contents",
    readingProgress: "Reading progress",
    line: "lines",
    noSections: "This article has no section headings; use the visual-line navigator instead.",
    untitledSection: (index: number) => `Section ${index}`,
    forthcoming: "Forthcoming",
    copy: "Copy",
    download: "Download",
    backToTop: "Back to top",
    credits: "Credits",
    author: "Author",
    roleLabels: {
      author: "Author", interviewee: "Interviewee", interviewer: "Interviewer", participant: "Participant",
      speaker: "Speaker", translator: "Translator", reviewer: "Reviewer", proofreader: "Proofreader", editor: "Editor",
    },
    roleMarks: {
      author: "A", interviewee: "G", interviewer: "I", participant: "P",
      speaker: "S", translator: "T", reviewer: "R", proofreader: "P", editor: "E",
    },
    annotation: "Notes",
    source: "Sources",
    annotationSingular: "note",
    sourceSingular: "source",
    noReference: (kind: string) => `This article has no ${kind.toLowerCase()}.`,
    firstReference: (kind: string) => `First ${kind}`,
    lastReference: (kind: string) => `Last ${kind}`,
    sourcePosition: "In the text",
    youAreReading: "You are reading",
    updateBoundary: "Article update boundary",
    readUntil: "Previously read to here",
    updatedBelow: "Updated material follows",
    settings: "Reading settings",
    globalNav: "Site navigation",
    theme: "Toggle color theme",
    close: "Close",
    back: "Back to",
    fontFamily: "Typeface",
    serif: "Serif",
    sans: "Sans serif",
    fontSize: "Text size",
    sizes: ["Small", "Medium", "Large"],
    sample: "A",
    lightTheme: "Use light theme",
    darkTheme: "Use dark theme",
    readingRecords: "Reading history",
    saveReadingRecords: "Save reading progress on this device",
    readingRecordsNote: "On by default. Progress stays in this browser and is never uploaded or synced.",
    clearCurrent: "Clear this article",
    clearAll: "Clear all history",
    clearAllConfirm: "Clear all reading history in this browser?",
    viewTable: "View table at the end",
    expand: "Expand",
    collapse: "Collapse",
    subsections: " subsections",
    articleActions: "Article actions",
    figure: "Figure",
    table: "Table",
    jumpToLine: "Jump by visual line",
    lineCountPending: "Calculating visual lines",
    articleContents: "Article contents",
    figureIndex: "Figures and tables",
    referenceJump: (kind: string) => `Jump to a ${kind.toLowerCase()} by number`,
    referenceInput: (kind: string, count: number) => `Enter a ${kind.toLowerCase()} number; ${count} total`,
    referenceCurrent: (kind: string, current: number) => `${kind} ${current}; enter a number to jump`,
    home: "Return to the Lab on Roof homepage",
    progressMessages: {
      appended: "New material has been added. Returning to where you last finished.",
      approximate: "This article has changed. Returning near your previous position.",
      restored: "Returned to your previous reading position.",
      disabled: "Reading history is no longer saved on this device.",
      disabledNotStored: "Saving is off for this page, but the browser could not remember the setting.",
      enabled: "Reading history is now saved on this device.",
      enabledNotStored: "Saving is on for this page, but the browser could not remember the setting.",
      clearCurrentFailed: "The browser could not clear this article’s reading history.",
      clearCurrentDone: "This article’s reading history has been cleared.",
      clearAllFailed: "The browser could not clear all reading history.",
      clearAllDone: "All reading history has been cleared.",
    },
  },
  ja: {
    brand: "屋頂現視研",
    nav: ["特集", "連載", "文庫", "概要"],
    introduction: "はじめに",
    contents: "目次",
    figures: "図表",
    bookContents: "全巻目次",
    readingProgress: "読書の進捗",
    line: "行",
    noSections: "本文に見出しはありません。表示行から移動できます。",
    untitledSection: (index: number) => `第${index}節`,
    forthcoming: "未公開",
    copy: "コピー",
    download: "ダウンロード",
    backToTop: "ページ上部へ",
    credits: "クレジット",
    author: "著者",
    roleLabels: {
      author: "著者", interviewee: "インタビュイー", interviewer: "聞き手", participant: "参加者",
      speaker: "登壇者", translator: "翻訳", reviewer: "レビュー", proofreader: "校閲", editor: "編集",
    },
    roleMarks: {
      author: "著", interviewee: "受", interviewer: "聞", participant: "談",
      speaker: "講", translator: "訳", reviewer: "評", proofreader: "校", editor: "編",
    },
    annotation: "注",
    source: "文献",
    annotationSingular: "注",
    sourceSingular: "文献",
    noReference: (kind: string) => `この本文に${kind}はありません。`,
    firstReference: (kind: string) => `${kind}の先頭`,
    lastReference: (kind: string) => `${kind}の末尾`,
    sourcePosition: "本文位置",
    youAreReading: "閲覧中",
    updateBoundary: "本文の更新箇所",
    readUntil: "前回はここまで",
    updatedBelow: "以下は更新内容",
    settings: "読書設定",
    globalNav: "サイトナビゲーション",
    theme: "配色を切り替える",
    close: "閉じる",
    back: "戻る",
    fontFamily: "書体",
    serif: "明朝体",
    sans: "ゴシック体",
    fontSize: "文字サイズ",
    sizes: ["小", "中", "大"],
    sample: "字",
    lightTheme: "ライトテーマに切り替える",
    darkTheme: "ダークテーマに切り替える",
    readingRecords: "読書履歴",
    saveReadingRecords: "この端末に読書位置を保存",
    readingRecordsNote: "初期設定はオンです。履歴はこのブラウザだけに保存され、送信も同期もされません。",
    clearCurrent: "この記事の履歴を消去",
    clearAll: "すべての履歴を消去",
    clearAllConfirm: "このブラウザの読書履歴をすべて消去しますか？",
    viewTable: "文末の表を見る",
    expand: "展開",
    collapse: "折りたたむ",
    subsections: "の下位見出し",
    articleActions: "記事の操作",
    figure: "図",
    table: "表",
    jumpToLine: "本文の表示行へ移動",
    lineCountPending: "表示行を計算中",
    articleContents: "記事目次",
    figureIndex: "図表索引",
    referenceJump: (kind: string) => `${kind}を番号で移動`,
    referenceInput: (kind: string, count: number) => `${kind}番号を入力（全${count}件）`,
    referenceCurrent: (kind: string, current: number) => `${kind}${current}。番号を入力して移動`,
    home: "屋頂現視研のトップページへ戻る",
    progressMessages: {
      appended: "追記があります。前回読み終えた位置に戻りました。",
      approximate: "本文が更新されています。前回の位置付近に戻りました。",
      restored: "前回の読書位置に戻りました。",
      disabled: "この端末への読書履歴の保存を停止しました。",
      disabledNotStored: "このページでは保存を停止しましたが、ブラウザに設定を記録できませんでした。",
      enabled: "この端末への読書履歴の保存を開始しました。",
      enabledNotStored: "このページでは保存を開始しましたが、ブラウザに設定を記録できませんでした。",
      clearCurrentFailed: "この記事の読書履歴を消去できませんでした。",
      clearCurrentDone: "この記事の読書履歴を消去しました。",
      clearAllFailed: "すべての読書履歴を消去できませんでした。",
      clearAllDone: "すべての読書履歴を消去しました。",
    },
  },
} as const;
