export interface ContributorLink {
  label: string;
  href: string;
}

export interface Contributor {
  /** Stable, URL-safe identity. Never derive links from a display name. */
  id: string;
  displayName: string;
  /** Historical spellings, romanizations and bylines accepted in old front matter. */
  aliases: readonly string[];
  /** Team membership is opt-in; publishing a contribution does not imply membership. */
  teamMember: boolean;
  entityType?: "person" | "organization";
  teamTitle?: string;
  teamOrder?: number;
  bio?: string;
  links?: readonly ContributorLink[];
}

/**
 * Public contributor identities used by published content.
 *
 * Keep `id` stable when a display name changes. Every authoring, translation,
 * editing or proofreading byline must resolve to one of these records before a
 * post can be built. Team data deliberately defaults to false until a person
 * has explicitly agreed to be listed on the About page.
 */
export const CONTRIBUTORS = [
  { id: "tu-shou-kai-gen-hao-er", displayName: "徒手开根号二", aliases: [], teamMember: false },
  { id: "dou-bao", displayName: "豆包", aliases: [], teamMember: false },
  { id: "kukhee-choo", displayName: "Kukhee Choo", aliases: [], teamMember: false, entityType: "person" },
  { id: "shuanglu-zuhe", displayName: "霜路组合", aliases: [], teamMember: false, entityType: "organization" },
  { id: "lu-jue", displayName: "路觉", aliases: [], teamMember: false, entityType: "person" },
  { id: "kongtongshanxia-sanjiaoya", displayName: "崆峒山下三角鸦", aliases: [], teamMember: false, entityType: "person" },
  { id: "saito-tamaki", displayName: "斋藤环", aliases: [], teamMember: false, entityType: "person" },
  { id: "nagasaki-hiroshi", displayName: "长崎浩", aliases: [], teamMember: false, entityType: "person" },
  { id: "xiaoqi-xiaowei", displayName: "骁骑校尉", aliases: [], teamMember: false, entityType: "person" },
  { id: "shizu-fumihiko", displayName: "志津史比古", aliases: [], teamMember: false, entityType: "person" },
  { id: "wei-guang", displayName: "微光", aliases: [], teamMember: false, entityType: "person" },
  {
    id: "roof-genshiken",
    displayName: "屋顶现视研",
    aliases: [],
    teamMember: false,
    entityType: "organization",
  },
  {
    id: "azuma-hiroki",
    displayName: "东浩纪",
    aliases: ["東浩紀", "Hiroki Azuma"],
    teamMember: false,
  },
  {
    id: "red-tea-seaweed",
    displayName: "红茶泡海苔",
    aliases: [],
    teamMember: false,
  },
  {
    id: "uno-tsunehiro",
    displayName: "宇野常宽",
    aliases: ["宇野常寛", "Tsunehiro Uno"],
    teamMember: false,
  },
  {
    id: "hood",
    displayName: "hood",
    aliases: ["HMS Hood"],
    teamMember: false,
  },
  {
    id: "harusaki-misora",
    displayName: "春埼美空",
    aliases: ["春琦美空", "春崎美空"],
    teamMember: false,
  },
  {
    id: "you-fisherman",
    displayName: "侑",
    aliases: ["fisherman"],
    teamMember: false,
  },
  { id: "gi", displayName: "Gi", aliases: [], teamMember: false },
  { id: "ian-condry", displayName: "伊恩·康德利", aliases: ["Ian Condry"], teamMember: false },
  { id: "ying-fan-kuli-bot01", displayName: "英翻苦力bot01", aliases: [], teamMember: false },
  { id: "wei-mu", displayName: "帷·幕", aliases: [], teamMember: false },
  { id: "hirooooo", displayName: "hirooooo", aliases: [], teamMember: false },
  { id: "electric-fan-huhu", displayName: "电扇呼呼", aliases: [], teamMember: false },
  { id: "wjk", displayName: "wjk", aliases: [], teamMember: false },
  { id: "shan-alter", displayName: "シャン[オルタ]", aliases: [], teamMember: false },
  { id: "san-mei-qie-zi", displayName: "三昧茄子", aliases: [], teamMember: false },
  { id: "panda-pai", displayName: "熊猫派", aliases: [], teamMember: false },
  { id: "fuqi-xue", displayName: "富崎 学", aliases: ["富崎学"], teamMember: false },
  { id: "yuan-yue", displayName: "远月", aliases: [], teamMember: false },
  { id: "qian-shen", displayName: "浅神", aliases: [], teamMember: false },
  { id: "t-jun", displayName: "T君", aliases: ["T君"], teamMember: false },
  { id: "da-ping-mao", displayName: "大平猫", aliases: [], teamMember: false },
  { id: "august-rush", displayName: "唯一指定真实August_Rush", aliases: [], teamMember: false },
  { id: "san-yi-jun", displayName: "三翼菌", aliases: [], teamMember: false },
  { id: "leontopodium-edelweiss", displayName: "Leontopodium Edelweiss", aliases: [], teamMember: false },
  { id: "shi-zai-gou-zi", displayName: "实在狗子", aliases: ["潜在狗子"], teamMember: false },
  { id: "sung-ho-kim", displayName: "Sung Ho Kim", aliases: [], teamMember: false },
  { id: "jeremiah", displayName: "Jeremiah", aliases: [], teamMember: false },
  { id: "chai-lairen", displayName: "柴来人", aliases: [], teamMember: false },
  { id: "yi-tiao", displayName: "一条", aliases: ["学级委员一条同学"], teamMember: false },
  { id: "jing-xi", displayName: "静希", aliases: [], teamMember: false },
  { id: "zhong-zi-mo", displayName: "钟子默", aliases: ["钟老师"], teamMember: false },
  { id: "zi-hou", displayName: "子厚", aliases: [], teamMember: false },
  { id: "lun-bo-lang", displayName: "伦勃朗", aliases: [], teamMember: false },
  { id: "circled-nine-sefu", displayName: "⑨瑟夫", aliases: [], teamMember: false },
  { id: "hephaestus", displayName: "hephaestus", aliases: ["hep"], teamMember: false },
  { id: "yan-ji-shi", displayName: "言几时", aliases: [], teamMember: false },
  { id: "su-yin", displayName: "速音", aliases: [], teamMember: false },
  { id: "austoria", displayName: "Austoria", aliases: ["AUS"], teamMember: false },
  { id: "suetonius", displayName: "Suetonius", aliases: [], teamMember: false },
  { id: "dusty-sky", displayName: "Dusty Sky", aliases: [], teamMember: false },
  { id: "yu-ban", displayName: "鱼板", aliases: ["🐟"], teamMember: false },
  { id: "chuang-zi", displayName: "窗子", aliases: [], teamMember: false },
  { id: "li-luo-hu-deng", displayName: "篱落呼灯", aliases: [], teamMember: false },
  { id: "yu-xiao-xing", displayName: "玉小兴", aliases: [], teamMember: false },
  {
    id: "ta-ta-jun-minkun",
    displayName: "塔塔君 Minkun",
    aliases: ["塔塔君"],
    teamMember: false,
  },
  { id: "yi-zhi-fei-ling-de-ling", displayName: "一只非0的O", aliases: ["一只非0的0"], teamMember: false },
  { id: "jing-xi-cao-shi-lang", displayName: "静希草十郎", aliases: [], teamMember: false },
  { id: "li-pao-pao", displayName: "李抛抛", aliases: [], teamMember: false },
  { id: "kvin", displayName: "kViN", aliases: [], teamMember: false },
  { id: "wo-you-yue-jia-san-qian", displayName: "我有越甲三千", aliases: [], teamMember: false },
  { id: "yu-zhou-shen-niu", displayName: "宇宙神牛", aliases: [], teamMember: false },
  { id: "san-hao-wen-xiong", displayName: "三好文雄", aliases: [], teamMember: false },
  { id: "bjorn-ole-kamm", displayName: "Björn-Ole Kamm", aliases: [], teamMember: false },
  { id: "wang-han", displayName: "王晗", aliases: [], teamMember: false },
  { id: "shen-de-yi-shi-xing-tai", displayName: "神的意识形态", aliases: [], teamMember: false },
  { id: "wu-you-zhi-ren", displayName: "乌有之人", aliases: [], teamMember: false },
  { id: "ivauke", displayName: "ivauke", aliases: [], teamMember: false },
  { id: "kong", displayName: "空", aliases: [], teamMember: false },
  { id: "yuan-da-nan", displayName: "元达南", aliases: [], teamMember: false },
  { id: "miyadai-shinji", displayName: "宫台真司", aliases: [], teamMember: false },
  { id: "rakugo-mimori", displayName: "落語三森", aliases: [], teamMember: false },
  { id: "ben-ti-shi-bao", displayName: "本体是包", aliases: [], teamMember: false },
  { id: "jie-luo-qi-bei-lin", displayName: "杰洛·齐贝林", aliases: [], teamMember: false },
  { id: "liu-shen", displayName: "六神", aliases: [], teamMember: false },
  { id: "shi-wen-zi", displayName: "十文字", aliases: [], teamMember: false },
  { id: "ludwigsama", displayName: "Ludwigsama", aliases: [], teamMember: false },
  { id: "mi-ze-wei-hua", displayName: "秘则为花", aliases: ["喵哥"], teamMember: false },
  { id: "njjgnuoy", displayName: "njjgnuoy", aliases: [], teamMember: false },
  { id: "jumbohard", displayName: "Jumbohard", aliases: [], teamMember: false },
  { id: "wei-yi-zhen-shi", displayName: "唯一真实", aliases: [], teamMember: false },
  {
    id: "fang-cao",
    displayName: "芳草",
    aliases: ["芳草进大门", "神圣芳草"],
    teamMember: false,
  },
  { id: "ophelia", displayName: "Ophelia", aliases: [], teamMember: false },
  {
    id: "zuo-zhe-jun-hou-yuan-hui-hui-zhang",
    displayName: "作者君的后援会会长",
    aliases: [],
    teamMember: false,
  },
  { id: "zhang-wu-ji", displayName: "张无忌", aliases: [], teamMember: false },
  { id: "ishida-miki", displayName: "石田美纪", aliases: [], teamMember: false },
  { id: "go-dai-yu-suke", displayName: "五代雄介", aliases: [], teamMember: false },
  { id: "yuan-qing-ri-yue-lang", displayName: "袁青日月郎", aliases: [], teamMember: false },
  { id: "pendulum-man", displayName: "pendulum man", aliases: [], teamMember: false },
  { id: "wyn", displayName: "wyn", aliases: [], teamMember: false },
  {
    id: "xian-nai-bing-gan",
    displayName: "鲜奶饼干",
    aliases: ["饼干", "cyclotron"],
    teamMember: false,
  },
  { id: "bie-ya-kuang", displayName: "别牙狂", aliases: [], teamMember: false },
  { id: "matsui-hiroshi", displayName: "松井广志", aliases: [], teamMember: false },
  { id: "mefls", displayName: "Mefls", aliases: [], teamMember: false },
  {
    id: "yi-ge-qu-wei-di-su-de-ren",
    displayName: "一个趣味低俗的人",
    aliases: [],
    teamMember: false,
  },
  { id: "jack-cade", displayName: "Jack Cade", aliases: [], teamMember: false },
  { id: "xin-su-sen-lin", displayName: "新宿森林", aliases: [], teamMember: false },
  { id: "shen-shui", displayName: "甚谁", aliases: [], teamMember: false },
  { id: "lin-pei-ying", displayName: "林沛颖", aliases: [], teamMember: false },
  { id: "hisui", displayName: "Hisui", aliases: [], teamMember: false },
  { id: "ako-de-hong", displayName: "Ako的红", aliases: [], teamMember: false },
  { id: "karatani-kojin", displayName: "柄谷行人", aliases: [], teamMember: false },
  { id: "ju-zi", displayName: "橘子", aliases: [], teamMember: false },
  { id: "mikan", displayName: "みかん", aliases: [], teamMember: false },
  { id: "kong-bu-ru-si", displayName: "恐怖如斯", aliases: [], teamMember: false },
  { id: "phaedo", displayName: "Phaedo", aliases: [], teamMember: false },
  { id: "phaedrus", displayName: "Phaedrus", aliases: [], teamMember: false },
  { id: "kafak", displayName: "KAFAK", aliases: [], teamMember: false },
  { id: "jia-su-qi", displayName: "加速器", aliases: [], teamMember: false },
  { id: "snoper-zhuo-er", displayName: "snoper卓尔", aliases: [], teamMember: false },
  { id: "matthew-flisfeder", displayName: "Matthew Flisfeder", aliases: ["Flisfeder"], teamMember: false },
  { id: "zu-guo-ren", displayName: "祖国人", aliases: [], teamMember: false },
  { id: "ao-ao-ao-jiao-de-feng-xue-zhang", displayName: "傲傲傲娇的风学长", aliases: [], teamMember: false },
  { id: "lieriheart", displayName: "lieriheart", aliases: [], teamMember: false },
  { id: "sheng-huo-zhi-xian-wan-jia", displayName: "生活支线玩家", aliases: [], teamMember: false },
  { id: "blur", displayName: "blur", aliases: [], teamMember: false },
  { id: "ying-yu", displayName: "頴彧", aliases: [], teamMember: false },
  { id: "si-jiu", displayName: "肆玖", aliases: [], teamMember: false },
  { id: "adrian-johnston", displayName: "Adrian Johnston", aliases: [], teamMember: false },
  { id: "yi-ban-tong-guo-animonk", displayName: "一般通过ANIMONK", aliases: [], teamMember: false },
  { id: "repapec-i", displayName: "repapec i", aliases: [], teamMember: false },
  { id: "odysseia", displayName: "ΟΔΥΣΣΕΙΑ", aliases: [], teamMember: false },
  { id: "fan-yi-ju", displayName: "烦一句", aliases: [], teamMember: false },
  { id: "you-da", displayName: "犹大", aliases: [], teamMember: false },
  { id: "hu-lian-wang-bu-ming-bai", displayName: "互联网不明白", aliases: [], teamMember: false },
  { id: "solntse", displayName: "Солнце", aliases: [], teamMember: false },
  { id: "subarashiki-hibi", displayName: "素晴らしき日々", aliases: [], teamMember: false },
  { id: "173-dai-xian-yu", displayName: "173代咸鱼", aliases: [], teamMember: false },
  { id: "yang-ji-chang-ke-qing", displayName: "养鸡场客卿", aliases: [], teamMember: false },
  { id: "kk", displayName: "kk", aliases: [], teamMember: false },
  { id: "hyacinth", displayName: "Hyacinth", aliases: [], teamMember: false },
  { id: "tu-yin", displayName: "兔引", aliases: [], teamMember: false },
  { id: "lv", displayName: "旅", aliases: [], teamMember: false },
  { id: "chai-zhen-tan", displayName: "柴侦探", aliases: [], teamMember: false },
  { id: "uekita-chiaki", displayName: "上北千明", aliases: [], teamMember: false },
  { id: "wen-tian", displayName: "问天", aliases: [], teamMember: false },
  { id: "ye-cai-yi-ri-fen", displayName: "野菜一日分", aliases: [], teamMember: false },
  { id: "gong-jiu-ji", displayName: "宫酒姬", aliases: [], teamMember: false },
  { id: "adam-lowenstein", displayName: "Adam Lowenstein", aliases: [], teamMember: false },
  { id: "will", displayName: "will", aliases: [], teamMember: false },
  { id: "pause-and-select", displayName: "pause and select", aliases: ["Pause and Select"], teamMember: false },
  {
    id: "qun-qing-qi-hao-lou",
    displayName: "群青七号楼",
    aliases: [],
    teamMember: false,
    entityType: "organization",
  },
  { id: "achamoth", displayName: "Achamoth", aliases: [], teamMember: false },
  { id: "elmy", displayName: "ElMY", aliases: [], teamMember: false },
  {
    id: "espen-aarseth",
    displayName: "Espen Aarseth",
    aliases: ["Espen J. Aarseth"],
    teamMember: false,
  },
  { id: "alexander-bird", displayName: "Alexander Bird", aliases: [], teamMember: false },
  { id: "alex", displayName: "Alex", aliases: [], teamMember: false },
  { id: "emma-tobin", displayName: "Emma Tobin", aliases: [], teamMember: false },
  { id: "teki", displayName: "Teki", aliases: [], teamMember: false },
  { id: "wang-xue-chuan", displayName: "王雪川", aliases: [], teamMember: false },
  { id: "genki-desu-ka", displayName: "元気ですか", aliases: [], teamMember: false },
  { id: "daniel-smith", displayName: "Daniel Smith", aliases: [], teamMember: false },
  { id: "john-protevi", displayName: "John Protevi", aliases: [], teamMember: false },
  { id: "lie-huo", displayName: "裂火", aliases: [], teamMember: false },
  { id: "a-ben-xi", displayName: "阿本希", aliases: [], teamMember: false },
  { id: "shui-jiao-de-aho", displayName: "睡觉的Aho", aliases: [], teamMember: false },
  { id: "daniel-stoljar", displayName: "Daniel Stoljar", aliases: [], teamMember: false },
  { id: "nic-damnjanovic", displayName: "Nic Damnjanovic", aliases: [], teamMember: false },
  { id: "luanzhao", displayName: "luanzhao", aliases: [], teamMember: false },
  { id: "yiban-tongguo-anima", displayName: "一般通过ANIMA", aliases: [], teamMember: false },
  { id: "qiguai-de-a-fa-nan-yuan", displayName: "奇怪的阿法南猿", aliases: [], teamMember: false },
  { id: "aho", displayName: "aho", aliases: [], teamMember: false },
  { id: "ban-jiu", displayName: "斑鸠", aliases: [], teamMember: false },
  {
    id: "you-hen-duo-mei-yong-de-shu-de-xue-wen-shao-nian",
    displayName: "有很多没用的书的学文少年",
    aliases: [],
    teamMember: false,
  },
  { id: "va-11-hall-a", displayName: "Va-11 Hall-A", aliases: [], teamMember: false },
  { id: "yun-he-you-quan", displayName: "運河遊犬", aliases: [], teamMember: false },
  { id: "linda-zagzebski", displayName: "Linda Zagzebski", aliases: [], teamMember: false },
  { id: "mao-da-meng", displayName: "猫大猛", aliases: [], teamMember: false },
  { id: "ji", displayName: "吉", aliases: [], teamMember: false },
  { id: "zhi-bu-shao", displayName: "治部少", aliases: [], teamMember: false },
  { id: "crossroad", displayName: "crossroad", aliases: [], teamMember: false },
  { id: "wan-zhong-song-bie-ci-ri", displayName: "晚钟送别此日", aliases: [], teamMember: false },
  { id: "theo-m-v-janssen", displayName: "Theo M. V. Janssen", aliases: [], teamMember: false },
  { id: "cjy", displayName: "cjy", aliases: [], teamMember: false },
  { id: "zoltan-gendler-szabo", displayName: "Zoltán Gendler Szabó", aliases: [], teamMember: false },
  { id: "zz", displayName: "zz", aliases: [], teamMember: false },
  { id: "zhe-kou", displayName: "折口", aliases: [], teamMember: false },
  { id: "oliver-perez-latorre", displayName: "Óliver Pérez-Latorre", aliases: [], teamMember: false },
  { id: "zhe-ge", displayName: "哲哥", aliases: [], teamMember: false },
  { id: "stephen-houlgate", displayName: "Stephen Houlgate", aliases: [], teamMember: false },
  { id: "you-dian-pai-pai", displayName: "有电拍拍", aliases: [], teamMember: false },
  { id: "an-hei-han-bing", displayName: "暗黑寒冰", aliases: [], teamMember: false },
  { id: "ayanami-rei", displayName: "绫波丽", aliases: [], teamMember: false },
  { id: "hannes-leitgeb", displayName: "Hannes Leitgeb", aliases: [], teamMember: false },
  { id: "andre-carus", displayName: "André Carus", aliases: [], teamMember: false },
  { id: "meowth", displayName: "Meowth", aliases: [], teamMember: false },
  { id: "shui-xiao-gui-koni", displayName: "水小鬼koni", aliases: [], teamMember: false },
  { id: "lin-chuan-deng-luo", displayName: "林川登罗", aliases: [], teamMember: false },
  { id: "andrew-bowie", displayName: "Andrew Bowie", aliases: [], teamMember: false },
  { id: "he-xiao-feng", displayName: "何啸风", aliases: [], teamMember: false },
  { id: "yan-guang", displayName: "艳光", aliases: [], teamMember: false },
  { id: "dan-zahavi", displayName: "Dan Zahavi", aliases: [], teamMember: false },
  { id: "fei-fei", displayName: "飞飞", aliases: [], teamMember: false },
  { id: "a-xi", displayName: "阿惜", aliases: [], teamMember: false },
  { id: "wo-da-xiao-san-sheng-ha-ha-ha", displayName: "我大笑三声哈哈哈", aliases: [], teamMember: false },
  { id: "wasted", displayName: "Wasted.", aliases: [], teamMember: false },
  { id: "zhen-hong", displayName: "真红", aliases: [], teamMember: false },
  { id: "xi-wen", displayName: "希文", aliases: [], teamMember: false },
  { id: "s-c", displayName: "S.C.", aliases: [], teamMember: false },
  { id: "raymond", displayName: "Raymond", aliases: [], teamMember: false },
  { id: "sasaki-shinsaku", displayName: "笹木信作", aliases: [], teamMember: false },
  { id: "daicon", displayName: "daicon", aliases: [], teamMember: false },
  { id: "scout", displayName: "スカウト", aliases: [], teamMember: false },
  { id: "a-ya", displayName: "啊呀", aliases: [], teamMember: false },
  { id: "sasaki-atsushi", displayName: "佐佐木敦", aliases: [], teamMember: false },
  { id: "mi-gang", displayName: "米岡", aliases: [], teamMember: false },
  { id: "ren-ji-er-lang", displayName: "人吉尔朗", aliases: ["人吉尔郎"], teamMember: false },
  { id: "de-ye-you-wo", displayName: "德野悠我", aliases: [], teamMember: false },
  { id: "guo-ke-li-de-mo-mo", displayName: "果壳里的墨墨", aliases: [], teamMember: false },
  { id: "qing-jin-metalh", displayName: "氢金_MetalH", aliases: [], teamMember: false },
  { id: "rocefactor", displayName: "rocefactor", aliases: [], teamMember: false },
  { id: "lu-ya", displayName: "鹿崖", aliases: [], teamMember: false },
  { id: "tina", displayName: "Tina", aliases: [], teamMember: false },
  { id: "yu-zhou-chen-ai", displayName: "宇宙尘埃", aliases: [], teamMember: false },
  { id: "far", displayName: "FAR", aliases: [], teamMember: false },
  { id: "c7", displayName: "C7", aliases: [], teamMember: false },
  { id: "shan-ze-zhi-mei", displayName: "伞泽直美", aliases: [], teamMember: false },
  { id: "yi-yang", displayName: "一样", aliases: [], teamMember: false },
  { id: "fahh", displayName: "fahh", aliases: [], teamMember: false },
  { id: "arkgrayhe", displayName: "Arkgrayhe", aliases: [], teamMember: false },
  { id: "liebestram", displayName: "Liebestram", aliases: [], teamMember: false },
  { id: "ying-ze", displayName: "萤泽", aliases: [], teamMember: false },
  { id: "gu-sen", displayName: "顾森", aliases: [], teamMember: false },
  { id: "tian-na", displayName: "天な", aliases: [], teamMember: false },
  { id: "bu-ai", displayName: "怖い", aliases: [], teamMember: false },
  { id: "xiong-jun", displayName: "熊君", aliases: [], teamMember: false },
  { id: "xiang-zhi", displayName: "相纸", aliases: [], teamMember: false },
  { id: "a-qi", displayName: "阿栖", aliases: [], teamMember: false },
  { id: "mou-bu-ke-xue-de-dou-bi", displayName: "某不科学的逗比", aliases: [], teamMember: false },
  { id: "brian-epstein", displayName: "Brian Epstein", aliases: [], teamMember: false },
  { id: "hufflepuff-piggy", displayName: "Hufflepuff piggy", aliases: [], teamMember: false },
  { id: "zhong-zheng-chang-shu", displayName: "仲正昌樹", aliases: [], teamMember: false },
  { id: "shan-yuan-yin", displayName: "杉原 音", aliases: [], teamMember: false },
  { id: "chuan-jing-runa", displayName: "川井ルナ", aliases: [], teamMember: false },
  { id: "otsuka-eiji", displayName: "大塚英志", aliases: [], teamMember: false },
  { id: "chiba-masaya", displayName: "千叶雅也", aliases: ["千葉雅也"], teamMember: false },
  { id: "nonnegative", displayName: "Nonnegative", aliases: [], teamMember: false },
  { id: "tomino-yoshiyuki", displayName: "富野由悠季", aliases: [], teamMember: false },
  { id: "ren-qi-kong-you", displayName: "人气空友", aliases: [], teamMember: false },
  { id: "luo-ji", displayName: "萝姬", aliases: [], teamMember: false },
  { id: "asada-akira", displayName: "浅田彰", aliases: [], teamMember: false },
  { id: "mari-ruti", displayName: "Mari Ruti", aliases: [], teamMember: false },
  { id: "another", displayName: "another", aliases: [], teamMember: false },
  { id: "xiao-xiao-xian-zhe", displayName: "小小贤者", aliases: [], teamMember: false },
  { id: "san", displayName: "伞", aliases: [], teamMember: false },
  { id: "e-jiang", displayName: "E酱", aliases: [], teamMember: false },
  { id: "warudo-chaos", displayName: "Warudo Chaos", aliases: [], teamMember: false },
  { id: "bo-er-ai-nan", displayName: "波尔艾南", aliases: [], teamMember: false },
  { id: "ren-shen-guo-wei-pi-shuang", displayName: "人参果味砒霜", aliases: [], teamMember: false },
  { id: "xiang-er", displayName: "香饵", aliases: [], teamMember: false },
  { id: "polaris", displayName: "Polaris", aliases: [], teamMember: false },
  { id: "wang-ling", displayName: "亡灵", aliases: [], teamMember: false },
  { id: "anno-hideaki", displayName: "庵野秀明", aliases: ["Hideaki Anno"], teamMember: false },
  { id: "bing-koori", displayName: "冰-koori", aliases: [], teamMember: false },
  { id: "aikawa-sho", displayName: "会川升", aliases: ["會川昇", "Sho Aikawa"], teamMember: false },
  { id: "otsuki-toshimichi", displayName: "大月俊伦", aliases: ["Toshimichi Otsuki"], teamMember: false },
  { id: "kinoshita-chika", displayName: "木下千花", aliases: [], teamMember: false },
  { id: "hiro", displayName: "hiro", aliases: [], teamMember: false },
  { id: "hamaguchi-ryusuke", displayName: "滨口龙介", aliases: ["濱口竜介"], teamMember: false },
  { id: "hasumi-shigehiko", displayName: "莲实重彦", aliases: ["蓮實重彦"], teamMember: false },
  { id: "miura-tetsuya", displayName: "三浦哲哉", aliases: [], teamMember: false },
  { id: "oguro-yuichiro", displayName: "小黑祐一郎", aliases: ["小黒祐一郎"], teamMember: false },
  { id: "izubuchi-yutaka", displayName: "出渕裕", aliases: ["Yutaka Izubuchi"], teamMember: false },
  { id: "suzuki-toshio", displayName: "铃木敏夫", aliases: ["鈴木敏夫", "Toshio Suzuki"], teamMember: false },
  { id: "oshii-mamoru", displayName: "押井守", aliases: ["Mamoru Oshii"], teamMember: false },
  { id: "ikuhara-kunihiko", displayName: "几原邦彦", aliases: ["Kunihiko Ikuhara"], teamMember: false },
  { id: "norizuki-rintaro", displayName: "法月纶太郎", aliases: ["法月綸太郎", "Rintaro Norizuki"], teamMember: false },
  { id: "pa-di-ya-de-pai-pai", displayName: "帕底亚的拍拍", aliases: [], teamMember: false },
  { id: "blank-brackets", displayName: "「　」", aliases: [], teamMember: false },
  { id: "stephane-mallarme", displayName: "斯蒂芬·马拉美", aliases: ["Stéphane Mallarmé"], teamMember: false },
  { id: "yang-sang-xi-huan-chi-shi-zi", displayName: "羊桑喜欢吃柿子", aliases: [], teamMember: false },
  { id: "shui-ye-bu-tui-dan-chun-dd", displayName: "谁也不推单纯DD", aliases: [], teamMember: false },
  { id: "sairai", displayName: "Sairai", aliases: [], teamMember: false },
  { id: "richard-rushton", displayName: "Richard Rushton", aliases: ["RICHARD RUSHTON"], teamMember: false },
  { id: "chun-qi-mei-kong", displayName: "春琪美空", aliases: [], teamMember: false },
  { id: "lockwood", displayName: "Lockwood", aliases: [], teamMember: false },
  { id: "ud-trn", displayName: "Ud Trn", aliases: [], teamMember: false },
  { id: "qiong-jie-ling", displayName: "茕孑零", aliases: [], teamMember: false },
  { id: "leif-wenar", displayName: "Leif Wenar", aliases: [], teamMember: false },
  { id: "you-tan-hua-yuan", displayName: "优昙华院", aliases: [], teamMember: false },
  { id: "xin-ba-bu-chi-su", displayName: "辛巴不吃素", aliases: [], teamMember: false },
  { id: "ilan", displayName: "ilan", aliases: [], teamMember: false },
  { id: "ryougi-shiki-lost", displayName: "両儀式所失去的", aliases: [], teamMember: false },
  { id: "james-welker", displayName: "James Welker", aliases: ["ジェームズ・ウェルカー"], teamMember: false },
  {
    id: "yin-nai-ping-pao-lu-er-liu-li-shi-suo-yu-er-94",
    displayName: "因奶瓶跑路而流离失所 鱼饵94",
    aliases: [],
    teamMember: false,
  },
  { id: "ryan-holmberg", displayName: "Ryan Holmberg", aliases: [], teamMember: false },
  { id: "dong-ye-lv-ren", displayName: "冬夜旅人", aliases: [], teamMember: false },
  { id: "cthugha", displayName: "Cthugha", aliases: [], teamMember: false },
  { id: "ju-yu", displayName: "举寓", aliases: [], teamMember: false },
  { id: "even", displayName: "Even", aliases: [], teamMember: false },
  { id: "kuan-dong", displayName: "款冬", aliases: [], teamMember: false },
  { id: "shiga-shiki", displayName: "志賀四季", aliases: [], teamMember: false },
  { id: "xin-tian-an-xiang", displayName: "心田安详", aliases: [], teamMember: false },
  { id: "kataoka-kazutake", displayName: "片岡一竹", aliases: [], teamMember: false },
  { id: "znqrwod", displayName: "ZnQRwoD", aliases: [], teamMember: false },
  { id: "disordered-heaven", displayName: "Disordered Heaven", aliases: [], teamMember: false },
  { id: "marc-steinberg", displayName: "Marc Steinberg", aliases: ["马克·斯坦伯格"], teamMember: false },
  { id: "celani", displayName: "celani", aliases: [], teamMember: false },
  { id: "qi-lin", displayName: "奇霖", aliases: [], teamMember: false },
  { id: "riri-chan", displayName: "りりちゃん", aliases: [], teamMember: false },
  { id: "shen-bi-tian-keng", displayName: "神必天坑", aliases: [], teamMember: false },
  { id: "ethci", displayName: "ethci", aliases: [], teamMember: false },
  { id: "salzivelm", displayName: "Salzivelm", aliases: [], teamMember: false },
  { id: "zhu-shang-qing", displayName: "竹上青", aliases: [], teamMember: false },
  { id: "yu-gong-you-zi", displayName: "雨宫优子", aliases: [], teamMember: false },
  { id: "ye-shen-ren-jing", displayName: "夜深人静", aliases: [], teamMember: false },
  { id: "underscore-editor", displayName: "-_-__-_-", aliases: [], teamMember: false },
  { id: "author-support-club-committee", displayName: "作者君的后援会委员", aliases: [], teamMember: false },
  { id: "kasai-kiyoshi", displayName: "笠井洁", aliases: ["笠井潔"], teamMember: false },
  { id: "tian-keng", displayName: "天坑", aliases: [], teamMember: false },
  { id: "ctfe", displayName: "CTFE", aliases: [], teamMember: false },
  { id: "yisensei04", displayName: "Yisensei04", aliases: [], teamMember: false },
  { id: "he-tun", displayName: "河豚", aliases: [], teamMember: false },
  { id: "shuang-zhu", displayName: "双柱", aliases: ["雙柱"], teamMember: false },
  {
    id: "omochinasai-anata-no-nozonda-sono-hoshi-o",
    displayName: "お持ちなさい、あなたの望んだその星を",
    aliases: ["お持ちなさい 、あなたの望んだその星を"],
    teamMember: false,
  },
  {
    id: "lorica-hamata-gao-hua",
    displayName: "想看穿着lorica hamata扔罗马长矛的高华怎么被破四旧",
    aliases: [],
    teamMember: false,
  },
  { id: "tai-xuan", displayName: "太玄", aliases: [], teamMember: false },
  { id: "furukawa-tomohiro", displayName: "古川知宏", aliases: [], teamMember: false },
  { id: "maeda-hisashi", displayName: "前田久", aliases: [], teamMember: false },
  { id: "kurisu-kurias", displayName: "栗栖Kurias", aliases: [], teamMember: false },
  { id: "animoni", displayName: "あにもに", aliases: [], teamMember: false },
  { id: "shiki", displayName: "shiki", aliases: [], teamMember: false },
  { id: "mu-wei-ren", displayName: "慕唯仁", aliases: [], teamMember: false },
  { id: "thomas-lamarre", displayName: "Thomas LaMarre", aliases: ["托马斯·拉马雷", "托马斯·拉马尔", "Thomas Lamarre", "拉马尔"], teamMember: false },
  { id: "gavin-walker", displayName: "Gavin Walker", aliases: ["加文·沃克"], teamMember: false },
  { id: "shan-zi-yi-tu", displayName: "单字一兔", aliases: [], teamMember: false },
  { id: "jiu-wan-cai-xiao", displayName: "九畹采萧", aliases: [], teamMember: false },
  { id: "mihara-ryotaro", displayName: "三原龙太郎", aliases: ["三原龍太郎"], teamMember: false },
  { id: "kong-tong-shan-xia-san-jiao-ya", displayName: "崆峒山下三脚鸦", aliases: [], teamMember: false },
  { id: "seigi-no-mikata", displayName: "正義の味方", aliases: [], teamMember: false },
  { id: "he-tun-ccc", displayName: "河豚ccc", aliases: [], teamMember: false },
  { id: "murakami-yu", displayName: "村上侑", aliases: ["Murakami Yuu"], teamMember: false },
  { id: "un-owen-aiyin", displayName: "U.N.オーエンは愛音なのか?", aliases: [], teamMember: false },
  { id: "yddd", displayName: "YDDD", aliases: [], teamMember: false },
  { id: "rex-salsamenta", displayName: "Rex salsamenta", aliases: [], teamMember: false },
  { id: "shui-se-wen-shu", displayName: "水色文书", aliases: [], teamMember: false },
  { id: "you-ling-zai-du-ling", displayName: "幽灵在都灵", aliases: [], teamMember: false },
  { id: "noirse", displayName: "noirse", aliases: [], teamMember: false },
  { id: "6x1", displayName: "6x1", aliases: [], teamMember: false },
  { id: "yi-ou-you", displayName: "伊鸥柚", aliases: [], teamMember: false },
  { id: "chandra-talpade-mohanty", displayName: "Chandra Talpade Mohanty", aliases: [], teamMember: false },
  { id: "zhu-xi", displayName: "竹兮", aliases: [], teamMember: false },
  { id: "rosemaire-tong", displayName: "Rosemarie Tong", aliases: ["Rosemaire Tong"], teamMember: false },
  { id: "tina-fernandes-botts", displayName: "Tina Fernandes Botts", aliases: [], teamMember: false },
  { id: "gabriel-tupinamba", displayName: "Gabriel Tupinambá", aliases: [], teamMember: false },
  { id: "wo-mo-fa-shao-nv-ne", displayName: "我魔法少女呢", aliases: [], teamMember: false },
  { id: "wu-guang-shi-se-de-la-ji-chang", displayName: "五光十色的垃圾场", aliases: [], teamMember: false },
  { id: "ynestra-king", displayName: "Ynestra King", aliases: [], teamMember: false },
  { id: "fool", displayName: "fool", aliases: [], teamMember: false },
  { id: "frederick-douglass", displayName: "Frederick Douglass", aliases: [], teamMember: false },
  { id: "aaron-s-moore", displayName: "Aaron S. Moore", aliases: ["阿伦·S.摩尔"], teamMember: false },
  { id: "kawamura-satofumi", displayName: "Satofumi Kawamura", aliases: ["川村覚文", "川村 覚文"], teamMember: false },
  { id: "katsuhiko-endo", displayName: "Katsuhiko Endo", aliases: ["遠藤克彦", "远藤克彦"], teamMember: false },
  { id: "fabian-schaefer", displayName: "Fabian Schäfer", aliases: ["法比安·舍费尔"], teamMember: false },
  { id: "max-ward", displayName: "Max Ward", aliases: ["马克斯·沃德"], teamMember: false },
  { id: "kitajima-hiro", displayName: "北島ひろ", aliases: [], teamMember: false },
  { id: "kopano", displayName: "KoPaNo", aliases: [], teamMember: false },
  { id: "trinh-t-minh-ha", displayName: "Trinh T. Minh-ha", aliases: [], teamMember: false },
  { id: "mac", displayName: "Mac", aliases: [], teamMember: false },
  { id: "valen", displayName: "Valen", aliases: [], teamMember: false },
  { id: "bei-chu-shiori", displayName: "北出栞", aliases: [], teamMember: false },
  { id: "geyi-platform", displayName: "格译平台", aliases: [], teamMember: false, entityType: "organization" },
  { id: "shou-ye-zi", displayName: "守夜子", aliases: [], teamMember: false },
  { id: "tatsumi-takayuki", displayName: "巽孝之", aliases: ["Takayuki Tatsumi"], teamMember: false },
  { id: "ming-zong", displayName: "明总", aliases: [], teamMember: false },
  { id: "harry-harootunian", displayName: "哈若图宁", aliases: ["Harry Harootunian"], teamMember: false },
  { id: "william-haver", displayName: "威廉·哈弗", aliases: ["William Haver"], teamMember: false },
  { id: "elena-lange", displayName: "埃莱娜·朗格", aliases: ["Elena Louisa Lange"], teamMember: false },
  { id: "modus", displayName: "Modus", aliases: [], teamMember: false },
  { id: "sakai-naoki", displayName: "酒井直树", aliases: ["Naoki Sakai", "酒井直樹"], teamMember: false },
  { id: "christian-uhl", displayName: "克里斯蒂安·乌尔", aliases: ["Christian Uhl"], teamMember: false },
  { id: "susan-archer-mann", displayName: "Susan Archer Mann", aliases: [], teamMember: false },
  { id: "wang-zhe-lin-ren-bu", displayName: "网哲邻人部", aliases: [], teamMember: false, entityType: "organization" },
  { id: "fujitsu-ryota", displayName: "藤津亮太", aliases: ["Ryota Fujitsu"], teamMember: false },
  { id: "zhong-ge-production", displayName: "中割Production", aliases: [], teamMember: false, entityType: "organization" },
  { id: "maikaze-tsumuji", displayName: "舞風つむじ", aliases: ["Tsumuji", "Tumuji"], teamMember: false },
  { id: "shiraki", displayName: "shiraki", aliases: [], teamMember: false },
  { id: "shi-hao-han", displayName: "石好汉", aliases: [], teamMember: false },
  { id: "kitahara-io", displayName: "北原依绪", aliases: [], teamMember: false },
  { id: "stevie-suan", displayName: "Stevie Suan", aliases: [], teamMember: false },
  { id: "sugita-shunsuke", displayName: "杉田俊介", aliases: ["Shunsuke Sugita"], teamMember: false },
  { id: "misaki-cho", displayName: "三咲町", aliases: [], teamMember: false },
  { id: "xing-yue-ru-jue", displayName: "星月如珏", aliases: [], teamMember: false },
  { id: "katsumi-nagaike", displayName: "Kazumi Nagaike", aliases: ["NAGAIKE"], teamMember: false },
  { id: "tomoko-aoyama", displayName: "Tomoko Aoyama", aliases: ["AOYAMA"], teamMember: false },
  { id: "surveiller", displayName: "Surveiller", aliases: [], teamMember: false },
  { id: "yu-yuan-ji", displayName: "郁远集", aliases: [], teamMember: false },
  { id: "hattori-keisuke", displayName: "服部恵典", aliases: [], teamMember: false },
  { id: "deepseek", displayName: "DeepSeek", aliases: [], teamMember: false, entityType: "organization" },
  { id: "sheng-ming-ti-zheng-wei-chi-cha-hua-hui", displayName: "生命体征维持茶话会", aliases: ["生命体征维护茶会"], teamMember: false, entityType: "organization" },
  { id: "deborah-cameron", displayName: "Deborah Cameron", aliases: ["DEBORAH CAMERON"], teamMember: false },
  { id: "ai-sheng-ming-ti-zheng-wei-chi-cha-hua-hui", displayName: "AI + 生命体征维持茶话会", aliases: [], teamMember: false, entityType: "organization" },
  { id: "cha-hua-hui", displayName: "茶话会", aliases: [], teamMember: false },
  { id: "di-di-ren-x-roof", displayName: "地底人X屋顶", aliases: [], teamMember: false, entityType: "organization" },
  { id: "ishioka-yoshiharu", displayName: "石岡良治", aliases: ["石冈良治", "Yoshiharu Ishioka"], teamMember: false },
  { id: "bing-ge", displayName: "冰格", aliases: [], teamMember: false },
  { id: "kai-xiao-yuan-che-de", displayName: "开校园车的", aliases: [], teamMember: false },
  { id: "uemura-taro", displayName: "上村太郎", aliases: ["Taro Uemura"], teamMember: false },
  { id: "kimoto-ken", displayName: "樹本健", aliases: [], teamMember: false },
  { id: "teramat", displayName: "てらまっと", aliases: ["Teramat"], teamMember: false },
  { id: "brian-m-white", displayName: "布莱恩·怀特", aliases: ["Brian M. White"], teamMember: false },
  { id: "recursion", displayName: "Recursion", aliases: [], teamMember: false },
  { id: "jaqueline-berndt", displayName: "杰奎琳·伯恩特", aliases: ["Jaqueline Berndt", "Jacqueline Berndt"], teamMember: false },
  { id: "sugii-hikaru", displayName: "杉井光", aliases: [], teamMember: false },
  { id: "akagi-tomohiro", displayName: "赤木智弘", aliases: [], teamMember: false },
  { id: "prevost-adele-elise", displayName: "Prévost, Adèle-Elise", aliases: ["Adèle-Elise Prévost"], teamMember: false },
  { id: "musebasement", displayName: "MUSEbasement", aliases: [], teamMember: false },
  { id: "kuronekos", displayName: "KuronekoS", aliases: [], teamMember: false },
  { id: "jalkkk", displayName: "JALKKK", aliases: [], teamMember: false },
  { id: "greta-gaard", displayName: "Greta Gaard", aliases: [], teamMember: false },
  { id: "mei-kong", displayName: "美空", aliases: [], teamMember: false },
  { id: "fujimoto-yukari", displayName: "藤本由香里", aliases: [], teamMember: false },
  { id: "zhao", displayName: "肇", aliases: [], teamMember: false },
  { id: "osugi-shigeo", displayName: "大杉重男", aliases: [], teamMember: false },
  { id: "doridori", displayName: "ドリドリ", aliases: [], teamMember: false },
  { id: "cfox", displayName: "Cfox", aliases: [], teamMember: false },
  { id: "emma-heaney", displayName: "Emma Heaney", aliases: [], teamMember: false },
  { id: "aliwen", displayName: "aliwen", aliases: ["Aliwen Muñoz"], teamMember: false },
  { id: "ni-ge-luo-ni", displayName: "尼格羅尼", aliases: [], teamMember: false },
  { id: "lin-xinzhi", displayName: "林新知", aliases: [], teamMember: false },
  { id: "ge-li-ya", displayName: "革利牙", aliases: [], teamMember: false },
  {
    id: "chahuahui-banweihui-bianyi",
    displayName: "茶话会班委会编译",
    aliases: ["茶话会班委会"],
    teamMember: false,
    entityType: "organization",
  },
  { id: "otsuki-kazushi", displayName: "乙木一史", aliases: [], teamMember: false },
  { id: "sflsnzyn", displayName: "SFLSNZYN", aliases: [], teamMember: false },
  { id: "pessimi", displayName: "ペシミ", aliases: [], teamMember: false },
  { id: "kojima-nobuyuki", displayName: "小岛伸之", aliases: [], teamMember: false },
  { id: "alexander-zahlten", displayName: "Alexander Zahlten", aliases: ["亚历山大·扎尔滕"], teamMember: false },
  { id: "kadobayashi-takeshi", displayName: "门林岳史", aliases: ["門林岳史"], teamMember: false },
  { id: "kimura-tomoya", displayName: "木村智哉", aliases: [], teamMember: false },
  { id: "fgccc", displayName: "fgccc", aliases: [], teamMember: false },
  { id: "paul-okane", displayName: "Paul O'Kane", aliases: ["保罗·欧康"], teamMember: false },
  { id: "matsuda-itsuki", displayName: "松田树", aliases: ["松田樹"], teamMember: false },
  { id: "fu-shi", displayName: "付石", aliases: [], teamMember: false },
  { id: "xia-sheng", displayName: "夏生", aliases: [], teamMember: false },
  { id: "ana-matilde-sousa", displayName: "Ana Matilde Sousa", aliases: [], teamMember: false },
  { id: "bot-miaomiao-tools", displayName: "bot的妙妙工具", aliases: [], teamMember: false },
  { id: "anonymous-interviewee", displayName: "匿名受访者", aliases: [], teamMember: false },
  { id: "non-shizai-gouzi", displayName: "非实在狗子", aliases: [], teamMember: false },
  { id: "zuan-shi", displayName: "钻石", aliases: [], teamMember: false },
  { id: "takizawa-fumina", displayName: "滝沢文那", aliases: [], teamMember: false },
  { id: "shigawa", displayName: "シガワ", aliases: [], teamMember: false },
] as const satisfies readonly Contributor[];

export type ContributorId = (typeof CONTRIBUTORS)[number]["id"];

const ASCII_ID_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const contributorById = new Map<ContributorId, (typeof CONTRIBUTORS)[number]>();
const contributorByName = new Map<string, (typeof CONTRIBUTORS)[number]>();

function normalizeName(value: string): string {
  return value.normalize("NFKC").trim().replace(/\s+/gu, " ").toLocaleLowerCase("zh-CN");
}

for (const contributor of CONTRIBUTORS) {
  if (!ASCII_ID_RE.test(contributor.id)) {
    throw new Error(`Contributor id must be lowercase ASCII kebab-case: ${contributor.id}`);
  }
  if (contributorById.has(contributor.id)) {
    throw new Error(`Duplicate contributor id: ${contributor.id}`);
  }
  contributorById.set(contributor.id, contributor);

  for (const name of [contributor.displayName, ...contributor.aliases]) {
    const normalized = normalizeName(name);
    const existing = contributorByName.get(normalized);
    if (existing && existing.id !== contributor.id) {
      throw new Error(`Contributor name or alias is ambiguous: ${name}`);
    }
    contributorByName.set(normalized, contributor);
  }
}

export function isContributorId(value: string): value is ContributorId {
  return contributorById.has(value as ContributorId);
}

export function getContributor(id: ContributorId): (typeof CONTRIBUTORS)[number] {
  const contributor = contributorById.get(id);
  if (!contributor) throw new Error(`Unknown contributor id: ${id}`);
  return contributor;
}

export function findContributor(id: string): (typeof CONTRIBUTORS)[number] | null {
  return contributorById.get(id as ContributorId) ?? null;
}

export function findContributorByName(name: string): (typeof CONTRIBUTORS)[number] | null {
  return contributorByName.get(normalizeName(name)) ?? null;
}

export function contributorEntityType(id: string): "person" | "organization" {
  const contributor = contributorById.get(id as ContributorId) as Contributor | undefined;
  return contributor?.entityType ?? "person";
}

export function getTeamMembers(): Contributor[] {
  return (CONTRIBUTORS as readonly Contributor[]).filter((contributor) => contributor.teamMember).sort(
    (a, b) => (a.teamOrder ?? Number.MAX_SAFE_INTEGER) - (b.teamOrder ?? Number.MAX_SAFE_INTEGER)
  );
}
